---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: fetch git submodules
    image: alpine/git
    commands:
    - git submodule init
    - git submodule update --recursive --remote

  - name: yarn
    image: node:14-alpine
    commands:
      - yarn

  - name: yarn lint
    image: node:14-alpine
    commands:
      - yarn lint

  - name: yarn build:dev
    image: node:14-alpine
    commands:
      - yarn build:dev

  - name: make release build and push to docker hub
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: dessalines/joinlemmy-site
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/tags/*

  - name: push to docker manifest
    image: plugins/manifest
    settings: 
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "dessalines/joinlemmy-site:${DRONE_TAG}"
      template: "dessalines/joinlemmy-site:${DRONE_TAG}-OS-ARCH"
      platforms:
        - linux/amd64
      ignore_missing: true
    when:
      ref:
      - refs/tags/*
