export const instance_stats = {
  stats: {
    crawled_instances: 11,
    total_users: 317737,
    users_active_day: 11253,
    users_active_week: 19504,
    users_active_month: 28342,
    users_active_halfyear: 45042,
    instance_details: [
      {
        domain: "lemm.ee",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.9",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 34364,
              activeHalfyear: 5668,
              activeMonth: 3813,
            },
            posts: 64706,
            comments: 853073,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "lemm.ee",
              sidebar:
                "# About this site\n\n* Sign-ups are open\n* E-mail verification is required\n* Downvotes are enabled\n* User community creation is enabled\n* Image uploads are enabled 4 weeks after account creation\n* Image upload limit is 500kb per image\n* We have a [policy for administration, moderation, and federation](https://lemm.ee/post/401063)\n* We have a [status page](https://status.lemm.ee/)\n\nFeel free to create or join communities for any topics that interest you!\n\n### Rules are simple:\n\n* No abusive language\n* No bigotry\n* No advertising\n* No pornography\n\n*There are additional rules for bots further below*\n\n-----\n\n#### Are you confused about how Lemmy works?\n\nCheck out our [Lemmy guide and F.A.Q.](https://lemm.ee/post/37715)!\n\nIt covers topics like:\n* What is Lemmy\n* How to join communities on other instances\n* ... and more!\n\n-----\n\n#### Do you find lemm.ee useful?\n\nYou can help secure the future of this instance by becoming a sponsor!\n\nClick the button below to find out more about how the intance is run and how you can support it on GitHub sponsors:\n\n[![GitHub Sponsors](https://img.shields.io/github/sponsors/sunaurus?style=for-the-badge)](https://github.com/sponsors/sunaurus)\n\nYou can also support on Ko-Fi as an alternative:\n\n[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/sunaurus)\n\n*Important note: donations are completely optional!*\n\n-----\n\n#### Additional rules for bots:\n\n* All bot accounts must be explicitly marked as bots\n* Bots must not vote on any posts or comments\n* Bots must disclose their specified purpose in their profile\n* Bots must not be responsible for the majority of content in any community\n",
              published: "2023-06-09T05:24:07.493111Z",
              updated: "2025-01-22T13:22:12.977245Z",
              icon: "https://lemm.ee/pictrs/image/da54d1e7-9f78-47f8-a04f-b73e20b86fb2.png",
              banner:
                "https://lemm.ee/pictrs/image/a87fdf78-c5ab-4e03-be06-93068444d3f2.png",
              description:
                "General-purpose Lemmy instance. New users and communities welcome! ",
              actor_id: "https://lemm.ee/",
              last_refreshed_at: "2023-06-09T05:31:14.719255Z",
              inbox_url: "https://lemm.ee/inbox",
              instance_id: 1,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: true,
              enable_nsfw: true,
              community_creation_admin_only: false,
              require_email_verification: true,
              private_instance: false,
              default_theme: "browser",
              default_post_listing_type: "All",
              hide_modlog_mod_names: true,
              application_email_admins: false,
              actor_name_max_length: 20,
              federation_enabled: true,
              captcha_enabled: true,
              captcha_difficulty: "medium",
              published: "2023-06-09T05:24:07.744978Z",
              updated: "2025-01-22T13:22:12.979587Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 34364,
              posts: 64706,
              comments: 853073,
              communities: 1583,
              users_active_day: 1532,
              users_active_week: 2604,
              users_active_month: 3813,
              users_active_half_year: 5668,
            },
          },
          version: "0.19.9",
        },
      },
      {
        domain: "lemmy.ml",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.9",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 53098,
              activeHalfyear: 3941,
              activeMonth: 2304,
            },
            posts: 150407,
            comments: 721804,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "Lemmy",
              sidebar:
                "[What is Lemmy.ml](https://lemmy.ml/post/70280)\n\n# Rules\n1. No bigotry - including racism, sexism, ableism, homophobia, transphobia, or xenophobia. [Code of Conduct](https://join-lemmy.org/docs/en/code_of_conduct.html).\n1. Be respectful, [especially when disagreeing](https://lemmy.ml/post/1140303). Everyone should feel welcome here.\n1. No porn.\n1. No Ads / Spamming.\n\n\nFeel free to ask questions over in:\n- [!lemmy_support](https://lemmy.ml/c/lemmy_support)\n- [Matrix Chat](https://matrix.to/#/#lemmy-space:matrix.org)\n- [Mastodon @LemmyDev](https://mastodon.social/@LemmyDev)",
              published: "2019-04-20T18:53:54.608882Z",
              updated: "2025-01-29T22:30:46.049161Z",
              icon: "https://lemmy.ml/pictrs/image/fa6d9660-4f1f-4e90-ac73-b897216db6f3.png",
              description:
                "A community of privacy and FOSS enthusiasts, run by Lemmy’s developers",
              actor_id: "https://lemmy.ml/",
              last_refreshed_at: "2022-07-09T17:56:21.988295Z",
              inbox_url: "https://lemmy.ml/inbox",
              instance_id: 394,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: true,
              enable_nsfw: true,
              community_creation_admin_only: false,
              require_email_verification: false,
              private_instance: false,
              default_theme: "browser",
              default_post_listing_type: "Local",
              hide_modlog_mod_names: true,
              application_email_admins: false,
              actor_name_max_length: 20,
              federation_enabled: true,
              captcha_enabled: false,
              captcha_difficulty: "medium",
              published: "2019-04-20T18:53:54.608882Z",
              updated: "2025-01-29T22:30:46.051081Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 53098,
              posts: 150407,
              comments: 721804,
              communities: 4548,
              users_active_day: 791,
              users_active_week: 1500,
              users_active_month: 2304,
              users_active_half_year: 3941,
            },
          },
          version: "0.19.9",
        },
      },
      {
        domain: "hexbear.net",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.8",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 28011,
              activeHalfyear: 2981,
              activeMonth: 1930,
            },
            posts: 363588,
            comments: 4863917,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "Hexbear",
              sidebar:
                "All posts and comments must follow the Hexbear [Code of Conduct](https://www.hexbear.net/code_of_conduct) as well as our [Terms of Service](https://www.hexbear.net/tos).\n\n[Hexbear Proposals](https://matrix.to/#%2F%23Hexbear_Proposals%3Achapo.chat%3Fvia=chapo.chat&via=matrix.org) a chapo.chat matrix room for site proposals, feedback, and appeals\n\nkota wrote a fast and simple read-only frontend similar to nitter, invidious, bibliogram, etc: https://diethex.net/\n\n",
              published: "2020-07-24T20:41:58.361900Z",
              updated: "2025-02-13T19:15:40.548481Z",
              icon: "https://chapo.chat/pictrs/image/d867623b-c069-4fb7-bc25-73bd0776362d.png",
              banner:
                "https://chapo.chat/pictrs/image/6d86f84d-ce1d-47b9-b03c-1467ff888636.png",
              description:
                "A leftist social platform centered around community building through discussion, shitposting memes, and sharing content.",
              actor_id: "https://hexbear.net/",
              last_refreshed_at: "2023-06-17T19:02:04.261280Z",
              inbox_url: "https://hexbear.net/inbox",
              instance_id: 1,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: false,
              enable_nsfw: true,
              community_creation_admin_only: true,
              require_email_verification: false,
              private_instance: false,
              default_theme: "darkly",
              default_post_listing_type: "Local",
              hide_modlog_mod_names: true,
              application_email_admins: false,
              actor_name_max_length: 80,
              federation_enabled: false,
              captcha_enabled: true,
              captcha_difficulty: "hard",
              published: "2020-07-24T20:41:58.361900Z",
              updated: "2025-02-13T19:15:40.556381Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 28011,
              posts: 363588,
              comments: 4863918,
              communities: 136,
              users_active_day: 869,
              users_active_week: 1436,
              users_active_month: 1930,
              users_active_half_year: 2981,
            },
          },
          version: "0.19.8",
        },
      },
      {
        domain: "feddit.org",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.5",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 2290,
              activeHalfyear: 1723,
              activeMonth: 1275,
            },
            posts: 24926,
            comments: 121751,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "feddit.org",
              sidebar:
                "[![Matrix Raum](https://img.shields.io/matrix/feddit.org%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Unser%20Matrix%20Raum)](https://matrix.to/#/#feddit.org:tchncs.de)  \n[![Matrix Space](https://img.shields.io/matrix/feddit.orgspace%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Unser%20Matrix%20Space)](https://matrix.to/#/#feddit.orgspace:tchncs.de)\n   \n[![Static Badge](https://img.shields.io/badge/Spende-über_Fediverse--Foundation-blue?style=plastic)](https://fediverse.foundation/spenden/)\n\n\nWir sind eine deutsch- und englischsprachige Lemmy Community und entwickelten uns aus feddit.de heraus. \n\nFeddit.org dient als Reddit-Alternative im Fediverse.\n     \nWir sehen uns als einen selbstbestimmten Raum, außerhalb der Kontrolle kommerzieller Tech-Unternehmen. \n\nNetiquette wird vorausgesetzt. Gepflegt wird ein respektvoller Umgang - ohne Hass, Hetze, Diskriminierung.     \n\nAlternative Oberflächen:  \n- [Photon](https://p.feddit.org/)\n- [Alexandrite](https://a.feddit.org/)\n- [Next](https://next.feddit.org/)\n- [mlmym](https://old.feddit.org/) (old)\n- [Tesseract](https://t.feddit.org/)\n\n[Werden euch Posts/Kommentare nicht angezeigt?](https://feddit.org/post/163939)\n\nDiese Community ist [spendenfinanziert](https://fediverse.foundation/spenden/) und wird von der [Fediverse Foundation](https://fediverse.foundation) unterstützt.   \n    \n\n\n::: spoiler Serverregeln \n\nWir tolerieren kein diskriminierendes Verhalten und keine Inhalte, die die Unterdrückung von Mitgliedern marginalisierter Gruppen fördern oder befürworten. Diese Gruppen können durch eine der folgenden Eigenschaften gekennzeichnet sein (obwohl diese Liste natürlich unvollständig ist):\n\n- ethnische Zugehörigkeit\n- Geschlechtsidentität oder Ausdruck\n- sexuelle Identität oder Ausdruck\n- körperliche Merkmale oder Alter\n- Behinderung oder Krankheit\n- Nationalität, Wohnsitz, Staatsbürgerschaft\n- Reichtum oder Bildung\n- Religionszugehörigkeit, Agnostizismus oder Atheismus\n     \nWir tolerieren kein bedrohliches Verhalten, Stalking und Doxxing. Wir tolerieren keine Belästigungen, einschließlich Brigading, Dogpiling oder jede andere Form des Kontakts mit einem Benutzer, der erklärt hat, dass er nicht kontaktiert werden möchte.\n\n- Sei respektvoll. Alle sind hier willkommen.\n- Kein Rassismus, Sexismus, Ableismus, Homophobie, oder anderweitige Xenophobie\n- Wir tolerieren kein Mobbing, einschließlich Beschimpfungen, absichtliches Misgendering oder Deadnaming.\n- Wir dulden keine gewalttätige nationalistische Propaganda, Nazisymbolik oder die Förderung der Ideologie des Nationalsozialismus.    \n- Aktionen, die diese Instanz oder ihre Leistung beschädigen sollen, können zur sofortigen Sperrung des Kontos führen.\n- Provokationen können nach Ermessen der Moderation entfernt werden\n- Toxisches Verhalten wird nicht geduldet\n- Keine Werbung und Eigenwerbung\n- Kein Spam\n- Keine Pornografie / Adult Content\n- In Deutschland, Österreich oder Schweiz illegale Inhalte werden gelöscht und können zur sofortigen Sperrung des Accounts führen.\n:::\n    \n\n::: spoiler Attribution \nThis text was partly adapted and modified from chaos.social. It is free to be adapted and remixed under the terms of the CC-BY (Attribution 4.0 International) license.\n:::        \n&nbsp;         \n[Datenschutzerklärung](https://wiki.apps.fedi.at/books/fediverse-foundation-announcements/page/datenschutzerklarung)    \n     \n[TOM](https://wiki.apps.fedi.at/books/fediverse-foundation-announcements/page/technische-und-organisatorische-massnahmen)     \n       \n\n---\n\n[![Matrix Room](https://img.shields.io/matrix/feddit.org%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Our%20Matrix%20Room)](https://matrix.to/#/#feddit.org:tchncs.de)  \n[![Matrix Space](https://img.shields.io/matrix/feddit.orgspace%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Our%20Matrix%20Space)](https://matrix.to/#/#feddit.orgspace:tchncs.de)\n     \nWe are a German and English-speaking Lemmy community that evolved from feddit.de.      \n      \nFeddit.org serves as a Reddit alternative in the Fediverse.     \n     \nWe see ourselves as a self-determined space, outside the control of commercial tech companies.      \n      \nNetiquette is expected. A respectful interaction is maintained - without hate, harassment, discrimination.   \n     \nAlternative UIs:\n\n- [Photon](https://p.feddit.org/)\n- [Alexandrite](https://a.feddit.org/)\n- [Next](https://next.feddit.org/)\n- [mlmym](https://old.feddit.org/) (old)\n- [Tesseract](https://t.feddit.org/)\n\n[Are you missing posts/comments?](https://feddit.org/post/163939)\n     \n::: spoiler Serverrules    \n\nWe do not tolerate discriminatory behavior or content that promotes or advocates the oppression of members of marginalized groups. These groups may be characterized by any of the following (though this list is of course incomplete):\n\n- ethnicity\n- gender identity or expression\n- sexual identity or expression\n- physical characteristics or age\n- disability or illness\n- nationality, residency, citizenship\n- wealth or education\n- religious affiliation, agnosticism, or atheism\n\nWe do not tolerate threatening behavior, stalking, and doxxing. We do not tolerate harassment, including brigading, dogpiling, or any other form of contact with a user who has stated that they do not wish to be contacted.\n\n- Be respectful. Everyone is welcome here.\n- No racism, sexism, ableism, homophobia, or other xenophobia\n- We do not tolerate bullying, including name-calling, intentional misgendering, or deadnaming.\n - We do not tolerate violent nationalist propaganda, Nazi symbolism or the promotion of the ideology of National Socialism. \n- Actions intended to damage this instance or its performance can lead to immediate blocking of the account.\n- Provocations can be removed at the discretion of the moderators\n- Toxic behavior will not be tolerated\n- No advertisements and self-advertisement\n- No spam\n- No pornography / adult content\n- Content that is illegal in Germany, Austria or Switzerland will be deleted and can lead to an immediate ban of the account.    \n:::   \n    \n\n\n::: spoiler Attribution \nThis text was partly adapted and modified from chaos.social. It is free to be adapted and remixed under the terms of the CC-BY (Attribution 4.0 International) license.\n:::        \n&nbsp;    \n[Data-Protection-Policy](https://wiki.apps.fedi.at/books/fediverse-foundation-announcements/page/data-protection-policy)     \n      \n[TOM](https://wiki.apps.fedi.at/books/fediverse-foundation-announcements/page/technical-and-organizational-measures)\n\nThis community is [powered by donations](https://fediverse.foundation/spenden/) and supported by [Fediverse Foundation](https://fediverse.foundation).    \n    \n[![Static Badge](https://img.shields.io/badge/Donate-about_Fediverse--Foundation-blue?style=plastic)](https://fediverse.foundation/spenden/)\n",
              published: "2024-06-21T09:03:05.284447Z",
              updated: "2025-02-12T02:00:10.862724Z",
              icon: "https://feddit.org/pictrs/image/3040be45-1c62-4f5a-8786-aeee71ad37e8.png",
              banner:
                "https://feddit.org/pictrs/image/60ffd481-236a-42ba-9a67-b812e45348d1.png",
              actor_id: "https://feddit.org/",
              last_refreshed_at: "2024-06-21T09:03:05.273496Z",
              inbox_url: "https://feddit.org/inbox",
              instance_id: 1,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: true,
              enable_nsfw: true,
              community_creation_admin_only: false,
              require_email_verification: false,
              private_instance: false,
              default_theme: "browser",
              default_post_listing_type: "Local",
              hide_modlog_mod_names: true,
              application_email_admins: true,
              actor_name_max_length: 20,
              federation_enabled: true,
              captcha_enabled: false,
              captcha_difficulty: "medium",
              published: "2024-06-21T09:03:05.390263Z",
              updated: "2025-02-12T02:00:10.875969Z",
              registration_mode: "RequireApplication",
              reports_email_admins: true,
              federation_signed_fetch: true,
            },
            counts: {
              site_id: 1,
              users: 2290,
              posts: 24926,
              comments: 121751,
              communities: 215,
              users_active_day: 570,
              users_active_week: 957,
              users_active_month: 1275,
              users_active_half_year: 1723,
            },
          },
          version: "0.19.5",
        },
      },
      {
        domain: "lemmygrad.ml",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.9",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 9950,
              activeHalfyear: 968,
              activeMonth: 633,
            },
            posts: 77044,
            comments: 446227,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "Lemmygrad",
              sidebar:
                '##### Rules\n\n1. No capitalist apologia / anti-communism.\n1. No bigotry - including racism, sexism, ableism, homophobia, transphobia, or xenophobia.\n1. Be respectful. This is a safe space where all comrades should feel welcome; this includes a warning against uncritical sectarianism.\n1. No porn or sexually explicit content (even if marked NSFW).\n1. No right-deviationists (patsocs, nazbols, Strasserists, Duginists, etc).\n\n---\n\nSince January 2023, the creation of new "Shit X Say" type communities is not allowed. Please post anything of that nature to [Shit Reactionaries Say](https://lemmygrad.ml/c/shitreactionariessay) or [Shit Ultras Say](https://lemmygrad.ml/c/shitultrassay).\n\n---\n\n[Public Matrix chatroom](https://element.io/app/#/room/#internationale:matrix.org)\n\n[Vetting-based Matrix space and homeserver for /c/GenZedong](https://lemmygrad.ml/post/1294067)\n\n[ProleWiki - the proletarian Marxist-Leninist encyclopedia](https://prolewiki.org)\n\n---\n\nThe following communities are for sectarian posting;\n - [Reddit Post Archive](https://lemmygrad.ml/c/reddit_post_archive)\n - [Leftist Infighting](https://lemmygrad.ml/c/leftistinfighting)\n\n🇵🇸From the River to the Sea, Palestine will be Free! 🇵🇸\n\n☭☭☭\n\n![](https://lemmygrad.ml/pictrs/image/xNL4hEII78.png)',
              published: "2019-08-16T23:14:21.070852Z",
              updated: "2024-11-21T11:59:44.271185Z",
              icon: "https://lemmygrad.ml/pictrs/image/beb2f32d-8884-49a4-b21c-7e3582c09b87.png",
              banner:
                "https://lemmygrad.ml/pictrs/image/79ab2f62-5b6b-47fc-be4d-2809b9f6f01f.png",
              description:
                "A collection of Marxist communities, for memes, learning, news, discussion, media, or anything you like.",
              actor_id: "https://lemmygrad.ml/",
              last_refreshed_at: "2022-07-11T18:38:01.059847Z",
              inbox_url: "https://lemmygrad.ml/inbox",
              instance_id: 42,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: true,
              enable_nsfw: true,
              community_creation_admin_only: false,
              require_email_verification: false,
              private_instance: false,
              default_theme: "litely-red",
              default_post_listing_type: "Local",
              hide_modlog_mod_names: true,
              application_email_admins: false,
              actor_name_max_length: 20,
              federation_enabled: true,
              captcha_enabled: false,
              captcha_difficulty: "medium",
              published: "2019-08-16T23:14:21.070852Z",
              updated: "2024-11-21T11:59:44.274452Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 9950,
              posts: 77044,
              comments: 446227,
              communities: 681,
              users_active_day: 241,
              users_active_week: 464,
              users_active_month: 633,
              users_active_half_year: 968,
            },
          },
          version: "0.19.9",
        },
      },
      {
        domain: "feddit.uk",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.9",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 3634,
              activeHalfyear: 497,
              activeMonth: 340,
            },
            posts: 23548,
            comments: 110438,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "Feddit UK",
              sidebar:
                '### Who are we?\nFeddit.uk is UK-centric, with integration to the wider Fediverse.   \n  We tend to focus on UK-interest communities, others are welcome.\n\n  The name is a shortening of "federate it".  \n  Want to share a thing? Share it with the fediverse, or, fed-it.  \n- See it\n- Like it?\n- Feddit\n\n### What are the rules here?\n* No racism, sexism, homophobia, transphobia or xenophobia\n* No incitement of violence or promotion of violent ideologies\n* No harassment, dogpiling or doxxing of other users\n* Do not share intentionally false or misleading information\n* Do not spam or abuse network features.\n* Alt accounts are permitted, but all accounts must list each other in their bios.  \n\nRules apply on this instance, and when using an account from this instance to interact with other instances.  \n  Administrators may warn or ban for breaches of the rules, or the spirit of the rules.\n\n\n### Where should I start?\n\nIf you are new, say "hello" over at !welcome@feddit.uk. We can offer any specific help you might need there. Other than that...\n\n#### Here\n- !unitedkingdom@feddit.uk for general UK news.\n- !casualuk@feddit.uk for general chit-chat.\n- !uk_politics@feddit.uk for politics.\n- !memes@feddit.uk to watch us get arrested for stealing memes without a licence.\n- !askuk@feddit.uk to find out where to get a meme licence.\n- !andfinally@feddit.uk for silly news.\n\n#### Elsewhere\n- [Lemmyverse > communities](https://lemmyverse.net/communities)\n- !newtolemmy@lemmy.ca\n\n### Frontends\n\n* [Photon](https://p.feddit.uk/)\n* [Alexandrite](https://a.feddit.uk/)\n* ~~[Old](https://old.feddit.uk/)~~ - Currently unavailable \n\n### Donation Link\n\nThis site does not serve adverts.  \n  [![OpenCollective donate button](https://opencollective.com/feddituk/tiers/notier.svg?avatarHeight=72)](https://opencollective.com/feddituk)  \n  [![OpenCollective donor counter link](https://opencollective.com/feddituk/tiers/badge.svg)](https://opencollective.com/feddituk)\n\n### Contact \n\n[![Matrix](https://img.shields.io/matrix/feddit-uk-chat%3Amatrix.org?logo=matrix&amp%3BlogoColor=white&amp%3Blabel=Matrix)](https://matrix.to/#/#feddit.uk:matrix.org)\n\n### Uptime status\n* [UptimeRobot](https://stats.uptimerobot.com/XzEqqSB3Ay)\n* [Lemmy Meter](https://lemmy-meter.info/d/GeoFE5WIz/instance-health-breakdown?var-lemmy_instance=feddit.uk&amp%3Bkiosk=tv&amp%3BorgId=1)\n\n### Fediseer\n[![Fediseer guarantees](https://fediseer.com/api/v1/badges/guarantees/feddit.uk.svg)](https://gui.fediseer.com/instances/detail/feddit.uk)\n\n[![Fediseer endorsements](https://fediseer.com/api/v1/badges/endorsements/feddit.uk.svg)](https://gui.fediseer.com/instances/detail/feddit.uk)\n\n### Threads\n\nMeta\'s activitypub network has been blocked as a default.  \n  If you believe there is a good case for this not to be, please start a thread in the feddit.uk community.\n\n### Banner\n\nCredit for the iconic banner --> https://joelgoodman.net/\n![](https://feddit.uk/pictrs/image/069fc09d-c1f8-41b4-a538-4c5293058d84.png)',
              published: "2023-06-09T08:29:16.797362Z",
              updated: "2025-02-11T16:55:14.741405Z",
              icon: "https://feddit.uk/pictrs/image/9ee95d7b-7d6d-4194-98b4-06c7ba094d45.png",
              banner:
                "https://feddit.uk/pictrs/image/4ef6c72c-a4aa-4374-9402-4e1018d75544.webp",
              description: "A UK centric gateway into the fediverse.",
              actor_id: "https://feddit.uk/",
              last_refreshed_at: "2023-06-09T08:34:11.814022Z",
              inbox_url: "https://feddit.uk/inbox",
              instance_id: 1,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: true,
              enable_nsfw: false,
              community_creation_admin_only: false,
              require_email_verification: true,
              private_instance: false,
              default_theme: "browser",
              default_post_listing_type: "Local",
              hide_modlog_mod_names: true,
              application_email_admins: true,
              actor_name_max_length: 30,
              federation_enabled: true,
              captcha_enabled: true,
              captcha_difficulty: "medium",
              published: "2023-06-09T08:29:16.968852Z",
              updated: "2025-02-11T16:55:14.752470Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 3634,
              posts: 23548,
              comments: 110438,
              communities: 311,
              users_active_day: 139,
              users_active_week: 237,
              users_active_month: 340,
              users_active_half_year: 497,
            },
          },
          version: "0.19.9",
        },
      },
      {
        domain: "reddthat.com",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.9",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 4998,
              activeHalfyear: 486,
              activeMonth: 283,
            },
            posts: 100087,
            comments: 96948,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "Reddthat",
              sidebar:
                '## About Us\n\n- Reddthat [rules](https://reddthat.com/post/9701)\n- Signups Open\n- Email Optional\n- Downvotes Disabled\n- Image & Videos allowed (Up to 20MB)\n- Our status page: https://status.reddthat.com/ \n\n## Official Communities\nThese are the communities that are specifically for Reddthat users in some "Official" way. There are plenty of other equally important communities that call Reddthat home and can be found [here](https://reddthat.com/communities?listingType=Local&sort=TopMonth&page=1).\n\n::: spoiler Communities (Click to show)\n- Announcements Community:  !reddthat@reddthat.com\n- Reddthat Offtopic Community: !community@reddthat.com \n  - Why not make your first post here!\n:::\n\n\n## Alternate Web Interfaces\nThese are 3rd party applications hosted on the Reddthat infrastructure.\n::: spoiler Alternate Web Interfaces (Click to show)\n  - Photon: https://photon.reddthat.com/\n  - Next: https://next.reddthat.com/\n  - Alexandrite: https://alexandrite.reddthat.com/\n  - Voyager: https://voyager.reddthat.com/ (Mobile specific)\n  - "Old": https://old.reddthat.com/ (You might be familiar with this layout)\n:::\n\n\n## Funding\nOur instance is 100% community-funded. For more information read: [Funding &amp; Longevity](https://reddthat.com/post/25633) or click a donation link below!\n\n[![Image showing how many supporters Reddthat has](https://opencollective.com/reddthat/tiers/badge.svg)](https://opencollective.com/reddthat)\n\n::: spoiler Donation Links (Click to show)\n- Open Collective: https://opencollective.com/reddthat\n- Ko-Fi: https://ko-fi.com/reddthat\n- Crypto:\n  - [Donate Crypto (Trocador)](https://trocador.app/anonpay/?ticker_to=xmr&network_to=Mainnet&address=4286pC9NxdyTo5Y3Z9Yr9NN1PoRUE3aXnBMW5TeKuSzPHh6eYB6HTZk7W9wmAfPqJR1j684WNRkcHiP9TwhvMoBrUD9PSt3&donation=True&simple_mode=True&amount=0.0002&name=Reddthat&buttonbgcolor=9f6c59&bgcolor=9f6c59aa)\n  - [Donate Crypto (Trocador Onion)](http://trocadorfyhlu27aefre5u7zri66gudtzdyelymftvr4yjwcxhfaqsid.onion/anonpay/?ticker_to=xmr&network_to=Mainnet&address=4286pC9NxdyTo5Y3Z9Yr9NN1PoRUE3aXnBMW5TeKuSzPHh6eYB6HTZk7W9wmAfPqJR1j684WNRkcHiP9TwhvMoBrUD9PSt3&donation=True&simple_mode=True&amount=0.0002&name=Reddthat&buttonbgcolor=9f6c59&bgcolor=9f6c59aa)\n- XMR Directly: `4286pC9NxdyTo5Y3Z9Yr9NN1PoRUE3aXnBMW5TeKuSzPHh6eYB6HTZk7W9wmAfPqJR1j684WNRkcHiP9TwhvMoBrUD9PSt3`\n- LTC Directly: `ltc1qfs92f6d80jelhj6avwf9u7q5p7ldqqzg0twunw`\n:::\n\n## Thankyou\n\nThank-you for joining our little community. Because, without **you**, this community wouldn\'t be what it is today. \n\n❤️ Tiff ',
              published: "2023-06-06T23:25:23.202595Z",
              updated: "2025-02-12T21:57:08.770938Z",
              icon: "https://reddthat.com/pictrs/image/42d90347-70ff-42ef-a521-c0b8f2d94933.png",
              banner:
                "https://reddthat.com/pictrs/image/586618b3-41e9-426a-9d37-efe635da90c4.png",
              description:
                "A general Lemmy instance prioritising thoughtful communication and enjoyable communities. No email required and New communities always welcome!",
              actor_id: "https://reddthat.com/",
              last_refreshed_at: "2023-06-06T23:30:56.446820Z",
              inbox_url: "https://reddthat.com/inbox",
              instance_id: 1,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: false,
              enable_nsfw: true,
              community_creation_admin_only: false,
              require_email_verification: false,
              private_instance: false,
              default_theme: "browser-compact",
              default_post_listing_type: "All",
              hide_modlog_mod_names: true,
              application_email_admins: false,
              actor_name_max_length: 32,
              federation_enabled: true,
              captcha_enabled: true,
              captcha_difficulty: "easy",
              published: "2023-06-06T23:25:23.342058Z",
              updated: "2025-02-12T21:57:08.772788Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 4998,
              posts: 100087,
              comments: 96948,
              communities: 225,
              users_active_day: 112,
              users_active_week: 195,
              users_active_month: 283,
              users_active_half_year: 486,
            },
          },
          version: "0.19.9",
        },
      },
      {
        domain: "feddit.it",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.8",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 1988,
              activeHalfyear: 349,
              activeMonth: 207,
            },
            posts: 10342,
            comments: 36320,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "Feddit.it",
              sidebar:
                "#### Cos'è Fedd**it**\nFedd**it** è l'alternativa italiana a Reddit, basata sul software [Lemmy](https://www.lealternative.net/2022/04/06/cose-lemmy/), uno dei progetti più interessanti del [fediverso](https://peertube.uno/w/pvfVP39daxnZcxCJobSPwY?subtitle=it).\n\n#### Informazioni\nQuesto server di **Lemmy** è gestito da [Poliverso](https://poliverso.org/) e [Le Alternative](https://www.lealternative.net/).\n\n#### Regole\n\n🇮🇹 In questo server è necessario scrivere principalmente utilizzando la lingua italiana.\n\n🛎 Attualmente prima di poter aprire una comunità è necessaria l'approvazione degli amministratori [@poliverso@feddit.it](https://feddit.it/u/poliverso)  o [@skariko@feddit.it](https://feddit.it/u/skariko). Potete aprire una richiesta [cliccando qui](https://feddit.it/c/main), spiegando di cosa parlerà la comunità e come sarà gestita.\n\n📜 Ogni comunità sceglierà in autonomia le sue regole, i suoi moderatori e le sue esigenze. Non sarà tuttavia possibile aprire comunità con contenuti pornografici, illegali o con discriminazioni razziali o di genere.\n\n🚯 Le comunità politiche dovranno accettare e sottoscrivere una clausola sull'antifascismo.\n\n⛔️ Lo spam, i bot e i messaggi ripetuti o molesti saranno rimossi a prescindere dalle regole della comunità.\n\n♻️ Le comunità che non riusciranno ad auto-moderarsi verranno richiamate dagli admin e se non sarà possibile trovare una soluzione verranno eliminate.\n\n#### Come si mantiene Feddit?\n\n🧡 È un progetto indipendente e senza pubblicità, se volete potete aiutare la gestione di questo server con una piccola [donazione ricorrente su LiberaPay](https://liberapay.com/Feddit-it) oppure con una [donazione una tantum su Ko-Fi](https://ko-fi.com/fedditit).\n\nGrazie! 🧡\n\n📧 Per informazioni sull'istanza potete scrivere a lemmy@feddit.it",
              published: "2022-05-05T07:40:35.127186Z",
              updated: "2025-01-09T17:49:33.277442Z",
              icon: "https://feddit.it/pictrs/image/ab61b750-22e1-4fd8-b198-df1c1028e03f.png",
              description:
                "La migliore alternativa italiana e decentralizzata a Reddit, benvenutǝ!",
              actor_id: "https://feddit.it/",
              last_refreshed_at: "2022-07-27T07:34:07.401272Z",
              inbox_url: "https://feddit.it/inbox",
              instance_id: 779,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: true,
              enable_nsfw: true,
              community_creation_admin_only: true,
              require_email_verification: false,
              private_instance: false,
              default_theme: "browser",
              default_post_listing_type: "Local",
              hide_modlog_mod_names: true,
              application_email_admins: true,
              actor_name_max_length: 20,
              federation_enabled: true,
              captcha_enabled: false,
              captcha_difficulty: "medium",
              published: "2022-05-05T07:40:35.127186Z",
              updated: "2025-01-09T17:49:33.280352Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 1988,
              posts: 10342,
              comments: 36320,
              communities: 66,
              users_active_day: 58,
              users_active_week: 138,
              users_active_month: 207,
              users_active_half_year: 349,
            },
          },
          version: "0.19.8",
        },
      },
      {
        domain: "discuss.online",
        node_info: {
          version: "2.1",
          software: {
            name: "lemmy",
            version: "0.19.9",
          },
          protocols: ["activitypub"],
          usage: {
            users: {
              total: 2103,
              activeHalfyear: 306,
              activeMonth: 110,
            },
            posts: 5119,
            comments: 31965,
          },
          openRegistrations: true,
        },
        site_info: {
          site_view: {
            site: {
              id: 1,
              name: "Discuss Online",
              sidebar:
                "---\n\n# Welcome\n\nA community for anything and everything that's not terrible.\n\nLet's talk! But not like in a \"your partner saw you looking up bunnies with pancakes on their heads\" talk. Let's talk about anything and everything. Like how much we love bunnies with pancakes on their heads!\n\nIf you have questions about [Lemmy](https://join-lemmy.org/) or how the [fediverse](https://en.wikipedia.org/wiki/Fediverse) works, checkout [this post](https://discuss.online/post/646).\n\n## Sister sites\n- [Utter.Online (Mastodon)](https://utter.online/) - Open Registration\n- [Social.Photo (Pixelfed)](https://social.photo/) - Open Registration\n\n## Donations... if you can spare it\n- [Github Sponsors](https://github.com/sponsors/jgrim)\n- [Patreon](https://patreon.com/discussonline)\n- [OpenCollective](https://opencollective.com/discussonline/donate/)\n\n[![GitHub Sponsors](https://img.shields.io/github/sponsors/jgrim?style=for-the-badge)](https://github.com/sponsors/jgrim)\n![https://opencollective.com/discussonline/](https://opencollective.com/discussonline/tiers/badge.svg)\n\n---\n\n\n## Rules\n\n1. No bigotry - including racism, sexism, ableism, homophobia, transphobia, or xenophobia. Code of Conduct.\n2. Be respectful. Everyone should feel welcome here.\n3. No porn\n4. No Ads / Spamming.\n5. Follow the [Lemmy Code of Conduct](https://join-lemmy.org/docs/en/code_of_conduct.html)\n\n---\n\n## Links\n- [Mastodon: @discussonline@utter.online](https://utter.online/@discussonline)\n- [!new_here](https://discuss.online/c/new_here)\n- [Matrix: #online.discuss:discuss.online](https://matrix.to/#/#online.discuss:discuss.online)\n- [Matrix: #community-channels:discuss.online](https://matrix.to/#/#community-channels:discuss.online)\n- [Server Status](https://status.discuss.online/)\n- [Wiki](https://wiki.discuss.online/)\n\n---\n\n## Matrix\nThe matrix server is live with public rooms. Registration is open. Get your free @[you]@discuss.online username. [element.discuss.online](https://element.discuss.online/)\n\n---\n\n## Mastodon\nI have created a Mastodon server. Registration is open. Get your @[you]@utter.online username. [utter.online](https://utter.online/)\n\n---\n\n## Contact the admin\n- Matrix\n  - [@jgrim:discuss.online](http://matrix.to/#/@jgrim:discuss.online)\n- Mastodon\n  - [@jsonarray@utter.online](https://utter.online/@jsonarray)\n- Email\n  - [hello@discuss.online](mailto:hello@discuss.online)\n\n---\n## Metrics\n![](https://lemmy-status.org/api/v1/endpoints/_discuss-online/health/badge.svg)\n\n![](https://lemmy-status.org/api/v1/endpoints/_discuss-online/uptimes/7d/badge.svg)\n\n![](https://lemmy-status.org/api/v1/endpoints/_discuss-online/uptimes/24h/badge.svg)\n\n![](https://lemmy-status.org/api/v1/endpoints/_discuss-online/uptimes/1h/badge.svg)\n\n---\n\n\n[![](https://fediseer.com/api/v1/badges/endorsements/discuss.online.svg)](https://fediseer.com/api/v1/endorsements/discuss.online)\n[![](https://fediseer.com/api/v1/badges/guarantees/discuss.online.svg)](https://fediseer.com/api/v1/whitelist/discuss.online)\n\n---\n\n***The statistics below reflect the usage of local users.** Users can interact with any instance in the fediverse. Creating posts and comments count towards interactions. You may see a lot more activity than listed below generated from external users.*",
              published: "2023-06-09T02:34:06.725937Z",
              updated: "2025-02-11T14:14:34.588471Z",
              icon: "https://discuss.online/pictrs/image/1bbc1cb7-3eb1-484a-aeb9-e2b803a3e50a.png",
              banner:
                "https://discuss.online/pictrs/image/586dd377-8f96-43b9-9591-ac4ddb99b62c.png",
              description:
                "A general purpose Lemmy instance for discovery, fun, & sharing. It's a Lemmy place for all.",
              actor_id: "https://discuss.online/",
              last_refreshed_at: "2023-06-09T02:34:06.721210Z",
              inbox_url: "https://discuss.online/inbox",
              instance_id: 1,
            },
            local_site: {
              id: 1,
              site_id: 1,
              site_setup: true,
              enable_downvotes: true,
              enable_nsfw: true,
              community_creation_admin_only: false,
              require_email_verification: true,
              private_instance: false,
              default_theme: "browser-compact",
              default_post_listing_type: "All",
              hide_modlog_mod_names: true,
              application_email_admins: true,
              actor_name_max_length: 20,
              federation_enabled: true,
              captcha_enabled: true,
              captcha_difficulty: "easy",
              published: "2023-06-09T02:34:06.856177Z",
              updated: "2025-02-11T14:14:34.590897Z",
              registration_mode: "RequireApplication",
              reports_email_admins: true,
              federation_signed_fetch: false,
            },
            counts: {
              site_id: 1,
              users: 2103,
              posts: 5119,
              comments: 31965,
              communities: 77,
              users_active_day: 36,
              users_active_week: 69,
              users_active_month: 110,
              users_active_half_year: 306,
            },
          },
          version: "0.19.9",
        },
      },
    ],
  },
  recommended: {
    start_scan_instances: [
      "lemmy.ml",
      "lemm.ee",
      "feddit.it",
      "lemmygrad.ml",
      "reddthat.com",
      "lemmy.sdf.org",
      "feddit.uk",
      "hexbear.net",
      "discuss.online",
      "feddit.org",
      "lemmings.world",
      "lemmy.world",
    ],
    exclude: [
      "lemmy.glasgow.social",
      "ds9.lemmy.ml",
      "voyager.lemmy.ml",
      "enterprise.lemmy.ml",
      "nrsk.no",
      "burggit.moe",
      "lemmy.burger.rodeo",
      "bakchodi.org",
      "lemmy.comfysnug.space",
      "rqd2.net",
      "test.hexbear.net",
    ],
  },
};
