export const instance_stats = {
  stats: {
    crawled_instances: 2,
    instance_details: [
      {
        domain: "programming.dev",
        federated_instances: {},
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.5" },
          usage: {
            comments: 177694,
            posts: 17562,
            users: { activeHalfyear: 1695, activeMonth: 1024, total: 9512 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 177695,
              communities: 336,
              posts: 17562,
              site_id: 1,
              users: 9512,
              users_active_day: 345,
              users_active_half_year: 1695,
              users_active_month: 1024,
              users_active_week: 685,
            },
            local_site: {
              actor_name_max_length: 50,
              application_email_admins: false,
              captcha_difficulty: "medium",
              captcha_enabled: true,
              community_creation_admin_only: false,
              default_post_listing_type: "Local",
              default_theme: "browser",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2023-06-06T06:35:12.436871Z",
              registration_mode: "RequireApplication",
              reports_email_admins: true,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              slur_filter_regex: "(d4vendor)",
              updated: "2025-01-12T08:25:36.418040Z",
            },
            local_site_rate_limit: {
              comment: 999,
              comment_per_second: 600,
              image: 999,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 999,
              message_per_second: 60,
              post: 999,
              post_per_second: 600,
              published: "2023-06-06T06:35:12.438204Z",
              register: 999,
              register_per_second: 3600,
              search: 999,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://programming.dev/",
              banner:
                "https://programming.dev/pictrs/image/52f986a9-7020-4442-8224-6499d5e84ed2.png",
              description: "A collection of programming communities",
              icon: "https://programming.dev/pictrs/image/1e947440-0f0d-4768-ba4b-1480551e7cc9.png",
              id: 1,
              inbox_url: "https://programming.dev/inbox",
              instance_id: 1,
              last_refreshed_at: "2023-06-06T06:35:12.362138Z",
              name: "programming.dev",
              public_key: "",
              published: "2023-06-06T06:35:12.365276Z",
              sidebar:
                '# Welcome Programmers!\n[programming.dev](https://programming.dev) is a collection of programming communities and other topics relevant to software engineers, hackers, roboticists, hardware and software enthusiasts, and more.\n\nThe site is primarily english with some communities in other languages. We are connected to many other sites using the activitypub protocol that you can view posts from in the "all" tab while the "local" tab shows posts on our site.\n\n---\n\n`🔗` [Site with links to all relevant programming.dev sites](https://me.programming.dev)\n\n`🟩` Not a fan of the default UI? We have alternate frontends we host that you can view the same content from\n- [Tesseract](https://t.programming.dev)\n- [Photon](https://p.programming.dev/)\n- [Alexandrite](https://a.programming.dev/)\n- [Mlmym (old reddit-like)](https://old.programming.dev/)\n- [Voyager (mobile)](https://v.programming.dev/posts/programming.dev/local)\n\n`ℹ️` We have a [wiki site](https://wiki.programming.dev) that communities can host documents on\n\n---\n\n`⚖️` All users are expected to follow our [Code of Conduct](https://legal.programming.dev/docs/code-of-conduct/) and the other various documents on our [legal site](https://legal.programming.dev/)\n\n`❤️` The site is run by a team of volunteers. If youre interested in donating to help fund things such as server costs you can do so [here](https://github.com/sponsors/snowe2010/)\n\n`💬` We have a microblog site aimed towards programmers available at https://bytes.programming.dev\n\n`🛠️` We have a [forgejo instance](https://git.programming.dev) for hosting git repositories relating to our site and the fediverse. If you have a project that relates and follows our Code of Conduct feel free to host it there and if you have ideas for things to improve our sites feel free to create issues in the [relevant repositories](https://git.programming.dev/Programming.Dev). To go along with the instance we also have a [site for sharing small code snippets](https://blocks.programming.dev) that might be too small for their own repository.\n\n`🌲` We have a [discord server](https://discord.gg/SnUk3bKkNC) and a [matrix space](https://matrix.to/#/#p.d:matrix.org) for chatting with other members of the community. These are bridged to each other (so you can interact with people using matrix from discord and vice versa.\n\n![](https://lemmy-status.org/api/v1/endpoints/_programming-dev/uptimes/7d/badge.svg) ![](https://lemmy-status.org/api/v1/endpoints/_programming-dev/response-times/7d/badge.svg)\n\n### Fediseer\n[![](https://fediseer.com/api/v1/badges/endorsements/programming.dev.svg)](https://gui.fediseer.com/instances/detail/programming.dev)\n\n---',
              updated: "2025-01-12T08:25:36.043962Z",
            },
          },
          taglines: [],
          version: "0.19.5",
        },
      },
    ],
    total_users: 9513,
    users_active_day: 345,
    users_active_halfyear: 1695,
    users_active_month: 1024,
    users_active_week: 685,
  },
  recommended: {
    start_scan_instances: ["programming.dev", "lem.ph3j.com"],
    exclude: [
      "lemmy.glasgow.social",
      "ds9.lemmy.ml",
      "voyager.lemmy.ml",
      "enterprise.lemmy.ml",
      "nrsk.no",
      "burggit.moe",
      "lemmy.burger.rodeo",
      "bakchodi.org",
      "lemmy.comfysnug.space",
      "rqd2.net",
      "test.hexbear.net",
    ],
  },
};
