export const instance_stats = {
  stats: {
    crawled_instances: 11,
    instance_details: [
      {
        domain: "lemmy.world",
        federated_instances: {},
        geo_ip: null,
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.15-4-g508853653" },
          usage: {
            comments: 5950344,
            posts: 603113,
            users: { activeHalfyear: 24761, activeMonth: 14266, total: 186123 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 5950344,
              communities: 12832,
              posts: 603113,
              site_id: 1,
              users: 186123,
              users_active_day: 5792,
              users_active_half_year: 24761,
              users_active_month: 14266,
              users_active_week: 9772,
            },
            local_site: {
              actor_name_max_length: 26,
              application_email_admins: false,
              captcha_difficulty: "hard",
              captcha_enabled: true,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "All",
              default_sort_type: "Active",
              default_theme: "darkly-pureblack",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: true,
              hide_modlog_mod_names: false,
              id: 1,
              private_instance: false,
              published: "2023-06-01T07:01:46.267237Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              require_email_verification: true,
              site_id: 1,
              site_setup: true,
              updated: "2025-10-03T06:10:49.795146Z",
            },
            local_site_rate_limit: {
              comment: 50,
              comment_per_second: 600,
              image: 50,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 999,
              message_per_second: 60,
              post: 999,
              post_per_second: 60,
              published: "2023-06-01T07:01:46.283919Z",
              register: 20,
              register_per_second: 300,
              search: 100,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://lemmy.world/",
              banner:
                "https://lemmy.world/pictrs/image/d22b2935-f27b-49f0-81e7-c81c21088467.png",
              description: "A generic Lemmy server for everyone to use.",
              icon: "https://lemmy.world/pictrs/image/0fd47927-ca3a-4d2c-b2e4-a25353786671.png",
              id: 1,
              inbox_url: "https://lemmy.world/inbox",
              instance_id: 1,
              last_refreshed_at: "2023-06-01T07:01:46.123867Z",
              name: "Lemmy.World",
              public_key: "",
              published: "2023-06-01T07:01:46.127298Z",
              sidebar:
                "The World's Internet Frontpage  \nLemmy.World is a general-purpose Lemmy instance of various topics, for the entire world to use.\n\nBe polite and follow the rules ⚖ \nhttps://legal.lemmy.world/tos\n\n## Get started \nSee the [Getting Started Guide](https://support.lemmy.world/quickstart)\n\n## Donations 💗\nIf you would like to make a donation to support the cost of running this platform, please do so at the following donation URLs.\n\n**If you can, please use / switch to Ko-Fi, it has the lowest fees for us**\n\n[![Ko-Fi (Donate)](https://img.shields.io/badge/KoFi_Donate-FHFWorld-red?style=flat-square&logo=kofi&color=red)](https://ko-fi.com/fhfworld)\n\n[![Bunq (Donate)](https://img.shields.io/badge/Bunq_Donate-FHF-green?style=flat-square&logo=bunq&color=darkgreen)](https://bunq.me/fhf)\n\n[![Open Collective backers and sponsors](https://img.shields.io/opencollective/all/mastodonworld?style=flat-square&logo=opencollective&color=7FADF2)](https://opencollective.com/mastodonworld)\n\n[![Patreon](https://img.shields.io/badge/Patreon-MastodonWorld-green?style=flat-square&logo=patreon&color=lightblue)](https://patreon.com/mastodonworld)\n\n[![Liberapay patrons](https://img.shields.io/liberapay/patrons/fhf?style=flat-square&logo=liberapay)](https://en.liberapay.com/fhf)\n\n[![GitHub Sponsors](https://img.shields.io/github/sponsors/Fedihosting-Foundation?style=flat-square&logo=github&label=Sponsors)](https://github.com/sponsors/Fedihosting-Foundation)\n\n## Join the team 😎\n[Check out our team page to join](https://fedihosting.foundation/positions/)\n\n## Questions / Issues \n- Questions/issues post to [![Lemmy](https://img.shields.io/lemmy/support%40lemmy.world?style=flat-square&logo=lemmy&label=support%40lemmy.world&color=pink)](https://lemmy.world/c/support) \n- To open a ticket [![Static Badge](https://img.shields.io/badge/email-info%40lemmy.world-green?style=flat-square&logo=mailgun&color=blue)](mailto:info@lemmy.world)\n- Reporting is to be done via the reporting button under a post/comment.\n- [Additional Report Info HERE](https://legal.lemmy.world/bylaws/#25-content-reporting)\n\n- [Please note, you will NOT be able to comment or post while on a VPN or Tor connection](https://lemmy.world/post/11967676)\n\n## More Lemmy.World\n### Follow us for server news 🐘\n[![Mastodon Follow](https://img.shields.io/mastodon/follow/110952393950540579?domain=https%3A%2F%2Fmastodon.world&style=flat-square&logo=mastodon&color=6364FF)](https://mastodon.world/@LemmyWorld)\n\n### Chat 🗨\n[![Discord](https://img.shields.io/discord/1120387349864534107?style=flat-square&logo=discord&color=565EAE)](https://discord.gg/lemmyworld)\n\n[![Matrix](https://img.shields.io/matrix/lemmy.world_general%3Amatrix.org?style=flat-square&logo=matrix&color=blue)](https://matrix.to/#/#general:lemmy.world)\n\n## Alternative UIs\n- [https://a.lemmy.world/](https://a.lemmy.world/) - Alexandrite UI\n- [https://photon.lemmy.world/](https://photon.lemmy.world/) - Photon UI\n- [https://m.lemmy.world/](https://m.lemmy.world/) - Voyager mobile UI\n- [https://old.lemmy.world/](https://old.lemmy.world/) - A familiar UI\n- [https://blorp.lemmy.world/](https://blorp.lemmy.world/) - Blorp UI\n\n## Monitoring / Stats 🌐\n\n### Service Status 🔥\n#### https://status.lemmy.world/\n\n[![](https://lemmy-status.org/api/v1/endpoints/_lemmy-world/uptimes/24h/badge.svg)](https://lemmy-status.org/endpoints/_lemmy-world)\n\n[![](https://lemmy-status.org/api/v1/endpoints/_lemmy-world/uptimes/7d/badge.svg)](https://lemmy-status.org/endpoints/_lemmy-world)\n\n[![Mozilla HTTP Observatory Grade](https://img.shields.io/mozilla-observatory/grade/lemmy.world)](https://observatory.mozilla.org/analyze/lemmy.world)\n\n[![](https://lemmy-status.org/api/v1/endpoints/_lemmy-world/response-times/7d/badge.svg)](https://lemmy-status.org/endpoints/_lemmy-world)\n\n[![](https://lemmy-status.org/api/v1/endpoints/_lemmy-world/response-times/24h/badge.svg)](https://lemmy-status.org/endpoints/_lemmy-world)\n\n[![](https://fediseer.com/api/v1/badges/endorsements/lemmy.world.svg)](https://gui.fediseer.com/instances/detail/lemmy.world)\n\nLemmy.World is part of the [FediHosting Foundation](https://fedihosting.foundation/)\n\n[![](https://img.shields.io/badge/92291619-blue?style=flat-square&label=%F0%9F%94%8D+FediHosting+Foundation&color=blue)](https://www.oozo.nl/bedrijven/breda/breda-noord-west/muizenberg/3177475/fedihosting-foundation-stichting)\n\n[![](https://lemmy.world/pictrs/image/27c30ddd-f9f4-4de6-ab57-18b43395833a.png)](https://dash.lemmy.world/)",
              updated: "2025-10-03T06:10:49.793690Z",
            },
          },
          taglines: [],
          version: "0.19.15-4-g508853653",
        },
      },
      {
        domain: "lemmy.ml",
        federated_instances: {},
        geo_ip: { iso_code: "FR", name: "France" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.15" },
          usage: {
            comments: 933093,
            posts: 188169,
            users: { activeHalfyear: 3792, activeMonth: 2042, total: 56718 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 933095,
              communities: 4664,
              posts: 188170,
              site_id: 1,
              users: 56718,
              users_active_day: 672,
              users_active_half_year: 3792,
              users_active_month: 2042,
              users_active_week: 1345,
            },
            local_site: {
              actor_name_max_length: 20,
              application_email_admins: false,
              captcha_difficulty: "medium",
              captcha_enabled: false,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "Local",
              default_sort_type: "Active",
              default_theme: "browser",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2019-04-20T18:53:54.608882Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              updated: "2025-10-24T21:18:15.746113Z",
            },
            local_site_rate_limit: {
              comment: 6,
              comment_per_second: 600,
              image: 6,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 180,
              message_per_second: 60,
              post: 6,
              post_per_second: 600,
              published: "2023-02-01T07:21:12.099368Z",
              register: 10,
              register_per_second: 3600,
              search: 60,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://lemmy.ml/",
              description:
                "A community of privacy and FOSS enthusiasts, run by Lemmy’s developers",
              icon: "https://lemmy.ml/pictrs/image/fa6d9660-4f1f-4e90-ac73-b897216db6f3.png",
              id: 1,
              inbox_url: "https://lemmy.ml/inbox",
              instance_id: 394,
              last_refreshed_at: "2022-07-09T17:56:21.988295Z",
              name: "Lemmy",
              public_key: "",
              published: "2019-04-20T18:53:54.608882Z",
              sidebar:
                "[What is Lemmy.ml](https://lemmy.ml/post/70280)\n\n# Rules\n1. No bigotry - including racism, sexism, ableism, homophobia, transphobia, or xenophobia. [Code of Conduct](https://join-lemmy.org/docs/en/code_of_conduct.html).\n1. Be respectful, [especially when disagreeing](https://lemmy.ml/post/1140303). Everyone should feel welcome here.\n1. No porn.\n1. No Ads / Spamming.\n\n\nFeel free to ask questions over in:\n- [!lemmy_support](https://lemmy.ml/c/lemmy_support)\n- [Matrix Chat](https://matrix.to/#/#lemmy-space:matrix.org)\n- [Mastodon @LemmyDev](https://mastodon.social/@LemmyDev)",
              updated: "2025-10-24T21:18:15.743963Z",
            },
          },
          taglines: [],
          version: "0.19.15",
        },
      },
      {
        domain: "feddit.org",
        federated_instances: {},
        geo_ip: { iso_code: "AT", name: "Austria" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.12" },
          usage: {
            comments: 336401,
            posts: 57173,
            users: { activeHalfyear: 2321, activeMonth: 1568, total: 5356 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 336401,
              communities: 375,
              posts: 57173,
              site_id: 1,
              users: 5356,
              users_active_day: 684,
              users_active_half_year: 2321,
              users_active_month: 1568,
              users_active_week: 1142,
            },
            local_site: {
              actor_name_max_length: 20,
              application_email_admins: true,
              captcha_difficulty: "medium",
              captcha_enabled: true,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "Local",
              default_sort_type: "Active",
              default_theme: "browser",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: true,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2024-06-21T09:03:05.390263Z",
              registration_mode: "RequireApplication",
              reports_email_admins: true,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              updated: "2025-12-31T17:26:57.989186Z",
            },
            local_site_rate_limit: {
              comment: 50,
              comment_per_second: 600,
              image: 999,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 999,
              message_per_second: 60,
              post: 50,
              post_per_second: 600,
              published: "2024-06-21T09:03:05.404319Z",
              register: 2,
              register_per_second: 3600,
              search: 999,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://feddit.org/",
              banner:
                "https://feddit.org/pictrs/image/60ffd481-236a-42ba-9a67-b812e45348d1.png",
              icon: "https://feddit.org/pictrs/image/3040be45-1c62-4f5a-8786-aeee71ad37e8.png",
              id: 1,
              inbox_url: "https://feddit.org/inbox",
              instance_id: 1,
              last_refreshed_at: "2024-06-21T09:03:05.273496Z",
              name: "feddit.org",
              public_key: "",
              published: "2024-06-21T09:03:05.284447Z",
              sidebar:
                "[![Matrix Raum](https://img.shields.io/matrix/feddit.org%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Unser+Matrix+Raum)](https://matrix.to/#/#feddit.org:tchncs.de)  \n[![Matrix Space](https://img.shields.io/matrix/feddit.orgspace%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Unser+Matrix+Space)](https://matrix.to/#/#feddit.orgspace:tchncs.de)  \n[![Static Badge](https://img.shields.io/badge/Spende-%C3%BCber_Fediverse--Foundation-blue?style=plastic)](https://fediverse.foundation/spenden/)\n\n\nWir sind eine deutsch- und englischsprachige Lemmy Community und entwickelten uns aus feddit\\.de heraus.\n\nFeddit.org dient als Reddit-Alternative im Fediverse.\n\nWir sehen uns als einen selbstbestimmten Raum, außerhalb der Kontrolle kommerzieller Tech-Unternehmen.\n\nNetiquette wird vorausgesetzt. Gepflegt wird ein respektvoller Umgang - ohne Hass, Hetze, Diskriminierung.\n\nAlternative Oberflächen (von uns bereitgestellt):\n- [Photon](https://p.feddit.org/)\n- [Alexandrite](https://a.feddit.org/)\n- [Next](https://next.feddit.org/)\n- [mlmym](https://old.feddit.org/) (old)\n- [Tesseract](https://t.feddit.org/)\n\nWeitere Optionen wie mobile Apps könnt ihr z.B. auf [lemmyapps.com](https://www.lemmyapps.com/) finden.\n\n[Werden euch Posts/Kommentare nicht angezeigt?](https://feddit.org/post/163939)\n\nDiese Community ist [spendenfinanziert](https://fediverse.foundation/spenden/) und wird von der [Fediverse Foundation](https://fediverse.foundation/) unterstützt.\n\n::: spoiler Serverregeln \n\nWir tolerieren kein diskriminierendes Verhalten und keine Inhalte, die die Unterdrückung von Mitgliedern marginalisierter Gruppen fördern oder befürworten. Diese Gruppen können durch eine der folgenden Eigenschaften gekennzeichnet sein (obwohl diese Liste natürlich unvollständig ist):\n\n- ethnische Zugehörigkeit\n- Geschlechtsidentität oder Ausdruck\n- sexuelle Identität oder Ausdruck\n- körperliche Merkmale oder Alter\n- Behinderung oder Krankheit\n- Nationalität, Wohnsitz, Staatsbürgerschaft\n- Reichtum oder Bildung\n- Religionszugehörigkeit, Agnostizismus oder Atheismus\n     \nWir tolerieren kein bedrohliches Verhalten, Stalking und Doxxing. Wir tolerieren keine Belästigungen, einschließlich Brigading, Dogpiling oder jede andere Form des Kontakts mit einem Benutzer, der erklärt hat, dass er nicht kontaktiert werden möchte.\n\n- Sei respektvoll. Alle sind hier willkommen.\n- Kein Rassismus, Sexismus, Ableismus, Homophobie, oder anderweitige Xenophobie\n- Wir tolerieren kein Mobbing, einschließlich Beschimpfungen, absichtliches Misgendering oder Deadnaming.\n- Wir dulden keine gewalttätige nationalistische Propaganda, Nazisymbolik oder die Förderung der Ideologie des Nationalsozialismus.\n- Aktionen, die diese Instanz oder ihre Leistung beschädigen sollen, können zur sofortigen Sperrung des Kontos führen.\n- Provokationen können nach Ermessen der Moderation entfernt werden\n- Toxisches Verhalten wird nicht geduldet\n- Keine Werbung und Eigenwerbung\n- Kein Spam\n- Keine Pornografie / Adult Content\n- In Deutschland, Österreich oder Schweiz illegale Inhalte werden gelöscht und können zur sofortigen Sperrung des Accounts führen.\n:::\n\n::: spoiler Attribution \nThis text was partly adapted and modified from chaos.social. It is free to be adapted and remixed under the terms of the CC-BY (Attribution 4.0 International) license.\n:::\n\n[Datenschutzerklärung](https://wiki.fediverse.foundation/books/fediverse-foundation-announcements/page/datenschutzerklarung)\n\n[TOMs](https://wiki.fediverse.foundation/books/fediverse-foundation-announcements/page/technische-und-organisatorische-massnahmen)\n\n---\n\n[![Matrix Room](https://img.shields.io/matrix/feddit.org%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Our+Matrix+Room)](https://matrix.to/#/#feddit.org:tchncs.de)  \n[![Matrix Space](https://img.shields.io/matrix/feddit.orgspace%3Atchncs.de?server_fqdn=matrix.org&style=plastic&label=Our+Matrix+Space)](https://matrix.to/#/#feddit.orgspace:tchncs.de)\n[![Static Badge](https://img.shields.io/badge/Donate-via_Fediverse--Foundation-blue?style=plastic)](https://fediverse.foundation/en/donations/)\n\nWe are a German and English-speaking Lemmy community that evolved from feddit\\.de.\n\nFeddit.org serves as a Reddit alternative in the Fediverse.\n\nWe see ourselves as a self-determined space, outside the control of commercial tech companies.\n\nNetiquette is expected. A respectful interaction is maintained - without hate, harassment, discrimination.\n\nAlternative UIs (provided by us):\n- [Photon](https://p.feddit.org/)\n- [Alexandrite](https://a.feddit.org/)\n- [Next](https://next.feddit.org/)\n- [mlmym](https://old.feddit.org/) (old)\n- [Tesseract](https://t.feddit.org/)\n\nMore options like mobile apps can be found e.g. on [lemmyapps.com](https://www.lemmyapps.com/).\n\n[Are you missing posts/comments?](https://feddit.org/post/163939)\n\nThis community is [powered by donations](https://fediverse.foundation/en/donations/) and supported by the [Fediverse Foundation](https://fediverse.foundation/).\n\n::: spoiler Serverrules\n\nWe do not tolerate discriminatory behavior or content that promotes or advocates the oppression of members of marginalized groups. These groups may be characterized by any of the following (though this list is of course incomplete):\n\n- ethnicity\n- gender identity or expression\n- sexual identity or expression\n- physical characteristics or age\n- disability or illness\n- nationality, residency, citizenship\n- wealth or education\n- religious affiliation, agnosticism, or atheism\n\nWe do not tolerate threatening behavior, stalking, and doxxing. We do not tolerate harassment, including brigading, dogpiling, or any other form of contact with a user who has stated that they do not wish to be contacted.\n\n- Be respectful. Everyone is welcome here.\n- No racism, sexism, ableism, homophobia, or other xenophobia\n- We do not tolerate bullying, including name-calling, intentional misgendering, or deadnaming.\n - We do not tolerate violent nationalist propaganda, Nazi symbolism or the promotion of the ideology of National Socialism. \n- Actions intended to damage this instance or its performance can lead to immediate blocking of the account.\n- Provocations can be removed at the discretion of the moderators\n- Toxic behavior will not be tolerated\n- No advertisements and self-advertisement\n- No spam\n- No pornography / adult content\n- Content that is illegal in Germany, Austria or Switzerland will be deleted and can lead to an immediate ban of the account.    \n:::\n\n::: spoiler Attribution \nThis text was partly adapted and modified from chaos.social. It is free to be adapted and remixed under the terms of the CC-BY (Attribution 4.0 International) license.\n:::\n\n[Data-Protection-Policy](https://wiki.fediverse.foundation/books/fediverse-foundation-announcements/page/data-protection-policy)\n\n[TOMs](https://wiki.fediverse.foundation/books/fediverse-foundation-announcements/page/technical-and-organizational-measures)",
              updated: "2025-12-31T17:26:57.981040Z",
            },
          },
          taglines: [],
          version: "0.19.12",
        },
      },
      {
        domain: "hexbear.net",
        federated_instances: {},
        geo_ip: { iso_code: "FR", name: "France" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.14" },
          usage: {
            comments: 5300695,
            posts: 397929,
            users: { activeHalfyear: 2431, activeMonth: 1543, total: 29800 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 5300699,
              communities: 138,
              posts: 397929,
              site_id: 1,
              users: 29800,
              users_active_day: 780,
              users_active_half_year: 2431,
              users_active_month: 1543,
              users_active_week: 1207,
            },
            local_site: {
              actor_name_max_length: 80,
              application_email_admins: false,
              captcha_difficulty: "medium",
              captcha_enabled: true,
              community_creation_admin_only: true,
              default_post_listing_mode: "List",
              default_post_listing_type: "Local",
              default_sort_type: "Active",
              default_theme: "darkly",
              enable_downvotes: false,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2020-07-24T20:41:58.361900Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              updated: "2026-01-15T10:59:08.764638Z",
            },
            local_site_rate_limit: {
              comment: 12,
              comment_per_second: 300,
              image: 6,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 180,
              message_per_second: 60,
              post: 6,
              post_per_second: 600,
              published: "2023-06-17T20:29:44.499734Z",
              register: 4,
              register_per_second: 3600,
              search: 60,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://hexbear.net/",
              banner:
                "https://hexbear.net/pictrs/image/6d86f84d-ce1d-47b9-b03c-1467ff888636.png",
              description:
                "A leftist social platform centered around community building through discussion, shitposting memes, and sharing content.",
              icon: "https://hexbear.net/pictrs/image/d867623b-c069-4fb7-bc25-73bd0776362d.png",
              id: 1,
              inbox_url: "https://hexbear.net/inbox",
              instance_id: 2,
              last_refreshed_at: "2023-06-17T19:02:04.261280Z",
              name: "Hexbear",
              public_key: "",
              published: "2020-07-24T20:41:58.361900Z",
              sidebar:
                "All posts and comments must follow the Hexbear [Code of Conduct](https://www.hexbear.net/code_of_conduct) as well as our [Terms of Service](https://www.hexbear.net/tos).\n\n[Hexbear Matrix Space](https://matrix.to/#/#Hexbear:matrix.org) a chapo.chat matrix room\n\nkota wrote a fast and simple read-only frontend similar to nitter, invidious, bibliogram, etc: https://diethex.net/\n\n",
              updated: "2026-01-15T10:59:08.752524Z",
            },
          },
          taglines: [],
          version: "0.19.14",
        },
      },
      {
        domain: "lemmygrad.ml",
        federated_instances: {},
        geo_ip: { iso_code: "NO", name: "Norway" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.13" },
          usage: {
            comments: 508222,
            posts: 91772,
            users: { activeHalfyear: 1397, activeMonth: 689, total: 10815 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 508222,
              communities: 710,
              posts: 91772,
              site_id: 1,
              users: 10815,
              users_active_day: 238,
              users_active_half_year: 1397,
              users_active_month: 689,
              users_active_week: 477,
            },
            local_site: {
              actor_name_max_length: 20,
              application_email_admins: false,
              captcha_difficulty: "medium",
              captcha_enabled: false,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "Local",
              default_sort_type: "Active",
              default_theme: "litely-red",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2019-08-16T23:14:21.070852Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              updated: "2026-01-06T11:06:13.392057Z",
            },
            local_site_rate_limit: {
              comment: 6,
              comment_per_second: 600,
              image: 6,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 180,
              message_per_second: 60,
              post: 6,
              post_per_second: 600,
              published: "2023-02-01T00:00:50.074793Z",
              register: 10,
              register_per_second: 3600,
              search: 60,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://lemmygrad.ml/",
              banner:
                "https://lemmygrad.ml/pictrs/image/79ab2f62-5b6b-47fc-be4d-2809b9f6f01f.png",
              description:
                "A collection of Marxist communities, for memes, learning, news, discussion, media, or anything you like.",
              icon: "https://lemmygrad.ml/pictrs/image/beb2f32d-8884-49a4-b21c-7e3582c09b87.png",
              id: 1,
              inbox_url: "https://lemmygrad.ml/inbox",
              instance_id: 42,
              last_refreshed_at: "2022-07-11T18:38:01.059847Z",
              name: "Lemmygrad",
              public_key: "",
              published: "2019-08-16T23:14:21.070852Z",
              sidebar:
                '##### Rules\n\n1. No capitalist apologia / anti-communism.\n1. No bigotry - including racism, sexism, ableism, homophobia, transphobia, or xenophobia.\n1. Be respectful. This is a safe space where all comrades should feel welcome; this includes a warning against uncritical sectarianism. See [this post](https://lemmygrad.ml/post/10105758) for enforcement of this rule.\n1. No porn or sexually explicit content (even if marked NSFW).\n1. No right-deviationists (patsocs, nazbols, Strasserists, Duginists, etc).\n\n---\n\nSince January 2023, the creation of new "Shit X Say" type communities is not allowed. Please post anything of that nature to [Shit Reactionaries Say](https://lemmygrad.ml/c/shitreactionariessay) or [Shit Ultras Say](https://lemmygrad.ml/c/shitultrassay).\n\n---\n\n* [Vetting-based Matrix space and homeserver for /c/GenZedong](https://lemmygrad.ml/post/1294067)\n* [ProleWiki - the proletarian Marxist-Leninist encyclopedia](https://prolewiki.org/)\n* [Matapacos.dog - Mastodon instance (Federated Twitter)](https://toots.matapacos.dog/)\n* [TankieTube - PeerTube instance (Federated Youtube)](https://tankie.tube/)\n\n---\n\nThe following communities are for sectarian posting;\n - [Reddit Post Archive](https://lemmygrad.ml/c/reddit_post_archive)\n - [Leftist Infighting](https://lemmygrad.ml/c/leftistinfighting)\n\n🇵🇸From the River to the Sea, Palestine will be Free! 🇵🇸\n\n☭☭☭\n\n![](https://lemmygrad.ml/pictrs/image/xNL4hEII78.png)',
              updated: "2026-01-06T11:06:13.389033Z",
            },
          },
          taglines: [],
          version: "0.19.13",
        },
      },
      {
        domain: "feddit.uk",
        federated_instances: {},
        geo_ip: { iso_code: "DE", name: "Germany" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.14-feddit" },
          usage: {
            comments: 173434,
            posts: 32292,
            users: { activeHalfyear: 622, activeMonth: 377, total: 4546 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 173434,
              communities: 348,
              posts: 32292,
              site_id: 1,
              users: 4546,
              users_active_day: 176,
              users_active_half_year: 622,
              users_active_month: 377,
              users_active_week: 289,
            },
            local_site: {
              actor_name_max_length: 30,
              application_email_admins: true,
              captcha_difficulty: "medium",
              captcha_enabled: true,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "Local",
              default_sort_type: "Active",
              default_theme: "browser",
              enable_downvotes: true,
              enable_nsfw: false,
              federation_enabled: true,
              federation_signed_fetch: true,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2023-06-09T08:29:16.968852Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              require_email_verification: true,
              site_id: 1,
              site_setup: true,
              updated: "2025-12-04T04:27:31.632675Z",
            },
            local_site_rate_limit: {
              comment: 50,
              comment_per_second: 600,
              image: 2,
              image_per_second: 300,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 999,
              message_per_second: 60,
              post: 5,
              post_per_second: 900,
              published: "2023-06-09T08:29:16.974275Z",
              register: 999,
              register_per_second: 3600,
              search: 999,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://feddit.uk/",
              banner:
                "https://feddit.uk/pictrs/image/4ef6c72c-a4aa-4374-9402-4e1018d75544.webp",
              description: "A UK centric gateway into the fediverse.",
              icon: "https://feddit.uk/pictrs/image/1108a696-0e37-442e-aade-3a9b6f828d75.webp",
              id: 1,
              inbox_url: "https://feddit.uk/inbox",
              instance_id: 1,
              last_refreshed_at: "2023-06-09T08:34:11.814022Z",
              name: "Feddit UK",
              public_key: "",
              published: "2023-06-09T08:29:16.797362Z",
              sidebar:
                '### Who are we?\nFeddit.uk is UK-centric, with integration to the wider Fediverse.   \n  We tend to focus on UK-interest communities, others are welcome.\n\n  The name is a shortening of "federate it".  \n  Want to share a thing? Share it with the fediverse, or, fed-it.  \n- See it\n- Like it?\n- Feddit\n\n### What are the rules here?\n* No racism, sexism, homophobia, transphobia or xenophobia\n  * See our [guidelines on transphobia](https://guide.feddit.uk/politics/transphobia.html) for more detail\n* No incitement of violence or promotion of violent ideologies\n* No harassment, dogpiling or doxxing of other users\n* Do not share intentionally false or misleading information\n* Do not spam or abuse network features.\n* Alt accounts are permitted, but all accounts must list each other in their bios. \n* No generative AI content\n\nRules apply on this instance, and when using an account from this instance to interact with other instances.  \n  Administrators may warn or ban for breaches of the rules, or the spirit of the rules.\n\n### Where should I start?\n\nIf you are new, say "hello" over at !welcome@feddit.uk. We can offer any specific help you might need there. Other than that...\n\n#### Here\n- !unitedkingdom@feddit.uk for general UK news.\n- !casualuk@feddit.uk for general chit-chat.\n- !uk_politics@feddit.uk for politics.\n- !memes@feddit.uk to watch us get arrested for stealing memes without a licence.\n- !askuk@feddit.uk to find out where to get a meme licence.\n- !andfinally@feddit.uk for silly news.\n\n#### Elsewhere\n- [Lemmyverse > communities](https://lemmyverse.net/communities)\n- !newtolemmy@lemmy.ca\n\n### Frontends\n\n* [Photon](https://p.feddit.uk/)\n* [Alexandrite](https://a.feddit.uk/)\n* [Old](https://old.feddit.uk/)\n* [Blorp](https://b.feddit.uk/)\n\n### Donation Link\n\nThis site does not serve adverts.  \n  [![OpenCollective donate button](https://opencollective.com/feddituk/tiers/notier.svg?avatarHeight=72)](https://opencollective.com/feddituk)  \n  [![OpenCollective donor counter link](https://opencollective.com/feddituk/tiers/badge.svg)](https://opencollective.com/feddituk)\n\n### Contact \n\n[![Matrix](https://img.shields.io/matrix/feddit-uk-chat%3Amatrix.org?logo=matrix&amp%3BlogoColor=white&amp%3Blabel=Matrix)](https://matrix.to/#/#feddit.uk:matrix.org)\n\n### Uptime status\n* [UptimeRobot](https://stats.uptimerobot.com/XzEqqSB3Ay)\n* [Lemmy Meter](https://lemmy-meter.info/d/GeoFE5WIz/instance-health-breakdown?var-lemmy_instance=feddit.uk&amp%3Bkiosk=tv&amp%3BorgId=1)\n\n### Fediseer\n[![Fediseer guarantees](https://fediseer.com/api/v1/badges/guarantees/feddit.uk.svg)](https://gui.fediseer.com/instances/detail/feddit.uk)\n\n[![Fediseer endorsements](https://fediseer.com/api/v1/badges/endorsements/feddit.uk.svg)](https://gui.fediseer.com/instances/detail/feddit.uk)\n\n### Threads\n\nMeta\'s activitypub network has been blocked as a default.  \n  If you believe there is a good case for this not to be, please start a thread in the feddit.uk community.\n\n### Banner\n\nCredit for the iconic banner --> https://joelgoodman.net/',
              updated: "2025-12-04T04:27:31.631601Z",
            },
          },
          taglines: [],
          version: "0.19.14-feddit",
        },
      },
      {
        domain: "reddthat.com",
        federated_instances: {},
        geo_ip: null,
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.15" },
          usage: {
            comments: 139112,
            posts: 105610,
            users: { activeHalfyear: 516, activeMonth: 298, total: 5862 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 139114,
              communities: 258,
              posts: 105610,
              site_id: 1,
              users: 5862,
              users_active_day: 115,
              users_active_half_year: 516,
              users_active_month: 298,
              users_active_week: 199,
            },
            local_site: {
              actor_name_max_length: 32,
              application_email_admins: false,
              captcha_difficulty: "easy",
              captcha_enabled: true,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "All",
              default_sort_type: "Active",
              default_theme: "browser-compact",
              enable_downvotes: false,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2023-06-06T23:25:23.342058Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              updated: "2026-01-12T23:39:28.876404Z",
            },
            local_site_rate_limit: {
              comment: 3000,
              comment_per_second: 600,
              image: 300,
              image_per_second: 600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 12000,
              message_per_second: 60,
              post: 12000,
              post_per_second: 60,
              published: "2023-06-06T23:25:23.346744Z",
              register: 100,
              register_per_second: 600,
              search: 200,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://reddthat.com/",
              banner:
                "https://reddthat.com/pictrs/image/586618b3-41e9-426a-9d37-efe635da90c4.png",
              description:
                "A general Lemmy instance prioritising thoughtful communication and enjoyable communities. No email required and New communities always welcome!",
              icon: "https://reddthat.com/pictrs/image/42d90347-70ff-42ef-a521-c0b8f2d94933.png",
              id: 1,
              inbox_url: "https://reddthat.com/inbox",
              instance_id: 1,
              last_refreshed_at: "2023-06-06T23:30:56.446820Z",
              name: "Reddthat",
              public_key: "",
              published: "2023-06-06T23:25:23.202595Z",
              sidebar:
                '## About Us\n\n- Reddthat [rules](https://reddthat.com/post/9701)\n- Signups Open\n- Email Optional\n- Downvotes Disabled\n- Image & Videos allowed (Up to 20MB)\n- Our status page: https://status.reddthat.com/ \n\n## Official Communities\nThese are the communities that are specifically for Reddthat users in some "Official" way. There are plenty of other equally important communities that call Reddthat home and can be found [here](https://reddthat.com/communities?listingType=Local&sort=TopMonth&page=1).\n\n::: spoiler Communities (Click to show)\n- Announcements Community:  !reddthat@reddthat.com\n- Reddthat Offtopic Community: !community@reddthat.com \n  - Why not make your first post here!\n:::\n\n\n## Alternate Web Interfaces\nThese are 3rd party applications hosted on the Reddthat infrastructure.\n::: spoiler Alternate Web Interfaces (Click to show)\n  - Photon: https://photon.reddthat.com/\n  - Voyager: https://voyager.reddthat.com/ (Mobile specific)\n  - "Old": https://old.reddthat.com/ (You might be familiar with this layout)\n:::\n\n\n## Funding\nOur instance is 100% community-funded. For more information read: [Funding &amp; Longevity](https://reddthat.com/post/25633) or click a donation link below!\n\n[![Liberapay donate button. Please donate, the server needs food](https://liberapay.com/assets/widgets/donate.svg)](https://liberapay.com/reddthat/donate) - ![Image showing how many supporters Reddthat has](https://img.shields.io/liberapay/patrons/reddthat.svg?logo=liberapay)\n\n::: spoiler Donation Links (Click to show)\n- LiberaPay: https://liberapay.com/reddthat\n- Ko-Fi: https://ko-fi.com/reddthat\n- Crypto:\n  - [Donate Crypto (Trocador)](https://trocador.app/anonpay/?ticker_to=xmr&network_to=Mainnet&address=4286pC9NxdyTo5Y3Z9Yr9NN1PoRUE3aXnBMW5TeKuSzPHh6eYB6HTZk7W9wmAfPqJR1j684WNRkcHiP9TwhvMoBrUD9PSt3&donation=True&simple_mode=True&amount=0.0002&name=Reddthat&buttonbgcolor=9f6c59&bgcolor=9f6c59aa)\n  - [Donate Crypto (Trocador Onion)](http://trocadorfyhlu27aefre5u7zri66gudtzdyelymftvr4yjwcxhfaqsid.onion/anonpay/?ticker_to=xmr&network_to=Mainnet&address=4286pC9NxdyTo5Y3Z9Yr9NN1PoRUE3aXnBMW5TeKuSzPHh6eYB6HTZk7W9wmAfPqJR1j684WNRkcHiP9TwhvMoBrUD9PSt3&donation=True&simple_mode=True&amount=0.0002&name=Reddthat&buttonbgcolor=9f6c59&bgcolor=9f6c59aa)\n- XMR Directly: `4286pC9NxdyTo5Y3Z9Yr9NN1PoRUE3aXnBMW5TeKuSzPHh6eYB6HTZk7W9wmAfPqJR1j684WNRkcHiP9TwhvMoBrUD9PSt3`\n- LTC Directly: `ltc1qfs92f6d80jelhj6avwf9u7q5p7ldqqzg0twunw`\n:::\n\n## Thankyou\n\nThank-you for joining our little community. Because, without **you**, this community wouldn\'t be what it is today. \n\n❤️ Tiff ',
              updated: "2026-01-12T23:39:28.875979Z",
            },
          },
          taglines: [],
          version: "0.19.15",
        },
      },
      {
        domain: "lemmy.sdf.org",
        federated_instances: {},
        geo_ip: { iso_code: "US", name: "United States" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.11" },
          usage: {
            comments: 186564,
            posts: 20681,
            users: { activeHalfyear: 657, activeMonth: 264, total: 5020 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 186564,
              communities: 316,
              posts: 20681,
              site_id: 1,
              users: 5020,
              users_active_day: 109,
              users_active_half_year: 657,
              users_active_month: 264,
              users_active_week: 187,
            },
            local_site: {
              actor_name_max_length: 30,
              application_email_admins: true,
              captcha_difficulty: "medium",
              captcha_enabled: false,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "Local",
              default_sort_type: "Active",
              default_theme: "browser",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2023-06-06T20:45:31.571926Z",
              registration_mode: "RequireApplication",
              reports_email_admins: true,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              updated: "2025-04-04T02:27:59.103964Z",
            },
            local_site_rate_limit: {
              comment: 9999,
              comment_per_second: 600,
              image: 9999,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 9999,
              message_per_second: 60,
              post: 9999,
              post_per_second: 600,
              published: "2023-06-06T20:45:31.577982Z",
              register: 999,
              register_per_second: 3600,
              search: 9999,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://lemmy.sdf.org/",
              banner:
                "https://lemmy.sdf.org/pictrs/image/d8da609c-8179-4e74-ab1d-df221f636e5d.png",
              description: "A Lemmy instance hosted by the SDF.ORG",
              icon: "https://lemmy.sdf.org/pictrs/image/28cea32f-f1f8-4225-97a4-58542dd4ffd5.png",
              id: 1,
              inbox_url: "https://lemmy.sdf.org/inbox",
              instance_id: 1,
              last_refreshed_at: "2023-06-06T20:46:34.527050Z",
              name: "SDF Chatter",
              public_key: "",
              published: "2023-06-06T20:45:31.452816Z",
              updated: "2025-04-04T02:27:59.101746Z",
            },
          },
          taglines: [],
          version: "0.19.11",
        },
      },
      {
        domain: "feddit.it",
        federated_instances: {},
        geo_ip: { iso_code: "FI", name: "Finland" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.14" },
          usage: {
            comments: 45858,
            posts: 12398,
            users: { activeHalfyear: 330, activeMonth: 159, total: 2410 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 45858,
              communities: 76,
              posts: 12398,
              site_id: 1,
              users: 2410,
              users_active_day: 43,
              users_active_half_year: 330,
              users_active_month: 159,
              users_active_week: 90,
            },
            local_site: {
              actor_name_max_length: 20,
              application_email_admins: true,
              captcha_difficulty: "medium",
              captcha_enabled: false,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "Local",
              default_sort_type: "Active",
              default_theme: "browser",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2022-05-05T07:40:35.127186Z",
              registration_mode: "RequireApplication",
              reports_email_admins: false,
              require_email_verification: false,
              site_id: 1,
              site_setup: true,
              updated: "2025-11-04T13:20:02.351498Z",
            },
            local_site_rate_limit: {
              comment: 6,
              comment_per_second: 600,
              image: 30,
              image_per_second: 3600,
              import_user_settings: 1,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 90,
              message_per_second: 30,
              post: 6,
              post_per_second: 600,
              published: "2023-02-08T09:30:43.216895Z",
              register: 10,
              register_per_second: 360,
              search: 60,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://feddit.it/",
              description:
                "La migliore alternativa italiana e decentralizzata a Reddit, benvenutǝ!",
              icon: "https://feddit.it/pictrs/image/ab61b750-22e1-4fd8-b198-df1c1028e03f.png",
              id: 1,
              inbox_url: "https://feddit.it/inbox",
              instance_id: 779,
              last_refreshed_at: "2022-07-27T07:34:07.401272Z",
              name: "Feddit.it",
              public_key: "",
              published: "2022-05-05T07:40:35.127186Z",
              sidebar:
                "#### Cos'è Fedd**it**\nFedd**it** è l'alternativa italiana a Reddit, basata sul software [Lemmy](https://www.lealternative.net/2022/04/06/cose-lemmy/), uno dei progetti più interessanti del [fediverso](https://peertube.uno/w/pvfVP39daxnZcxCJobSPwY?subtitle=it).\n\n#### Informazioni\nQuesto server di **Lemmy** è gestito da [Poliverso](https://poliverso.org/) e [Le Alternative](https://www.lealternative.net/).\n\n#### Regole\n\n🇮🇹 In questo server è necessario scrivere principalmente utilizzando la lingua italiana.\n\n🛎 È ora possibile aprire una nuova comunità in maniera del tutto autonoma. Per farlo basterà premere in alto nel menù **Crea Comunità** e inserirne i dati necessari. Le comunità senza post né commenti dopo diversi mesi verranno cancellate previo contatto con il proprio creatore.\n\n📜 Ogni comunità sceglierà in autonomia le sue regole, i suoi moderatori e le sue esigenze. Non sarà tuttavia possibile aprire comunità con contenuti pornografici, illegali o con discriminazioni razziali o di genere.\n\n🚯 Le comunità politiche dovranno accettare e sottoscrivere una clausola sull'antifascismo.\n\n⛔️ Lo spam, i bot e i messaggi ripetuti o molesti saranno rimossi a prescindere dalle regole della comunità.\n\n♻️ Le comunità che non riusciranno ad auto-moderarsi verranno richiamate dagli admin e se non sarà possibile trovare una soluzione verranno eliminate.\n\n#### Come si mantiene Feddit?\n\n🧡 È un progetto indipendente e senza pubblicità, se volete potete aiutare la gestione di questo server con una piccola [donazione ricorrente su LiberaPay](https://liberapay.com/Feddit-it) oppure con una [donazione una tantum su Ko-Fi](https://ko-fi.com/fedditit).\n\nIl server utilizzato è quello di [Hetzner](https://hetzner.cloud/?ref=ms8NgG4wXs5W), in Finlandia. Se volete provarlo potete ottenere 20€ gratuiti con [questo link](https://hetzner.cloud/?ref=ms8NgG4wXs5W) e noi riceveremo un aiuto sotto forma di credito da usare proprio per mantenere Feddit.\n\nGrazie! 🧡\n\n📧 Per informazioni sull'istanza potete scrivere a lemmy@feddit.it",
              updated: "2025-11-04T13:20:02.349626Z",
            },
          },
          taglines: [],
          version: "0.19.14",
        },
      },
      {
        domain: "discuss.online",
        federated_instances: {},
        geo_ip: { iso_code: "US", name: "United States" },
        node_info: {
          openRegistrations: true,
          protocols: ["activitypub"],
          software: { name: "lemmy", version: "0.19.15" },
          usage: {
            comments: 47384,
            posts: 14323,
            users: { activeHalfyear: 168, activeMonth: 89, total: 2404 },
          },
          version: "2.1",
        },
        site_info: {
          admins: [],
          all_languages: [],
          blocked_urls: [],
          custom_emojis: [],
          discussion_languages: [],
          site_view: {
            counts: {
              comments: 47384,
              communities: 100,
              posts: 14323,
              site_id: 1,
              users: 2404,
              users_active_day: 33,
              users_active_half_year: 168,
              users_active_month: 89,
              users_active_week: 62,
            },
            local_site: {
              actor_name_max_length: 20,
              application_email_admins: true,
              captcha_difficulty: "hard",
              captcha_enabled: true,
              community_creation_admin_only: false,
              default_post_listing_mode: "List",
              default_post_listing_type: "All",
              default_sort_type: "Active",
              default_theme: "browser-compact",
              enable_downvotes: true,
              enable_nsfw: true,
              federation_enabled: true,
              federation_signed_fetch: false,
              hide_modlog_mod_names: true,
              id: 1,
              private_instance: false,
              published: "2023-06-09T02:34:06.856177Z",
              registration_mode: "RequireApplication",
              reports_email_admins: true,
              require_email_verification: true,
              site_id: 1,
              site_setup: true,
              updated: "2025-08-17T23:14:12.259246Z",
            },
            local_site_rate_limit: {
              comment: 999,
              comment_per_second: 60,
              image: 50,
              image_per_second: 3600,
              import_user_settings: 9999999,
              import_user_settings_per_second: 86400,
              local_site_id: 1,
              message: 999,
              message_per_second: 60,
              post: 999,
              post_per_second: 60,
              published: "2023-06-20T00:07:26.626064Z",
              register: 5,
              register_per_second: 300,
              search: 100,
              search_per_second: 600,
            },
            site: {
              actor_id: "https://discuss.online/",
              banner:
                "https://discuss.online/pictrs/image/586dd377-8f96-43b9-9591-ac4ddb99b62c.png",
              description:
                "A general purpose instance for discovery, fun, & sharing. It's a welcoming place for all.",
              icon: "https://discuss.online/pictrs/image/1bbc1cb7-3eb1-484a-aeb9-e2b803a3e50a.png",
              id: 1,
              inbox_url: "https://discuss.online/inbox",
              instance_id: 1,
              last_refreshed_at: "2023-06-09T02:34:06.721210Z",
              name: "Discuss Online",
              public_key: "",
              published: "2023-06-09T02:34:06.725937Z",
              sidebar:
                "**Welcome to discuss.online!**\n\nHome for interesting conversation, discovery, and fun. Everyone is welcome!\n\n# Guidelines\n\ndiscuss.online aims to enrich the lives of everyone it touches. Please be kind as you use it.\n\nRead the [posting guidelines](https://wiki.discuss.online/view/Guidelines), but remember that the guidelines are fuzzy and imprecise, because the admins have final say.\n\nSome NSFW content is fine if tagged appropriately, but no porn or hornyposting.\n\n# Support us ❤️\n\nIf you like discuss.online and are feeling generous, you can help by donating to offset the server costs:\n\n [![Github-sponsors](https://discuss.online/api/v3/image_proxy?url=https%3A%2F%2Fimg.shields.io%2Fbadge%2Fsponsor-30363D%3Fstyle%3Dfor-the-badge%26logo%3DGitHub-Sponsors%26logoColor%3D%23EA4AAA)](https://github.com/sponsors/jgrim)\n \n [![Patreon](https://discuss.online/api/v3/image_proxy?url=https%3A%2F%2Fimg.shields.io%2Fbadge%2FPatreon-F96854%3Fstyle%3Dfor-the-badge%26logo%3Dpatreon%26logoColor%3Dwhite)](https://patreon.com/discussonline)\n\n# Helpful Links\n- Chat with us: [#online.discuss:discuss.online](https://matrix.to/#/#online.discuss:discuss.online)\n- Server Status: https://status.discuss.online/\n- Ask your newbie questions here: [!new_here@discuss.online](https://discuss.online/c/new_here) \n- Check out our wiki: https://wiki.discuss.online/\n\n# Contact Admins\n- Send a Matrix message to one of the admins:\n  - [@jgrim:discuss.online](http://matrix.to/#/@jgrim:discuss.online)\n  - [@m_f:discuss.online](http://matrix.to/#/@m_f:discuss.online)\n  - [@lazyguru:discuss.online](http://matrix.to/#/@lazyguru:discuss.online)\n- Email: [hello@discuss.online](mailto:hello@discuss.online)\n\n![Fediseer Endorsements](https://discuss.online/api/v3/image_proxy?url=https%3A%2F%2Ffediseer.com%2Fapi%2Fv1%2Fbadges%2Fendorsements%2Fdiscuss.online.svg)",
              updated: "2025-08-17T23:14:12.257357Z",
            },
          },
          taglines: [],
          version: "0.19.15",
        },
      },
    ],
    total_users: 313574,
    users_active_day: 8685,
    users_active_halfyear: 37428,
    users_active_month: 21437,
    users_active_week: 14856,
  },
  recommended: {
    start_scan_instances: [
      "lemmy.ml",
      "lemm.ee",
      "feddit.it",
      "lemmygrad.ml",
      "reddthat.com",
      "lemmy.sdf.org",
      "feddit.uk",
      "hexbear.net",
      "discuss.online",
      "feddit.org",
      "lemmings.world",
      "lemmy.world",
    ],
    exclude: [
      "lemmy.glasgow.social",
      "ds9.lemmy.ml",
      "voyager.lemmy.ml",
      "enterprise.lemmy.ml",
      "nrsk.no",
      "burggit.moe",
      "lemmy.burger.rodeo",
      "bakchodi.org",
      "lemmy.comfysnug.space",
      "rqd2.net",
      "test.hexbear.net",
    ],
  },
};
